FROM rocker/r-ver:4.2.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config \
    libcurl4-openssl-dev libssl-dev libxml2-dev \
  && rm -rf /var/lib/apt/lists/*

RUN R -q -e "options(repos=c(CRAN='https://cloud.r-project.org')); install.packages(c('remotes','knitr','rmarkdown'))"

WORKDIR /tmp/pkg
COPY DESCRIPTION DESCRIPTION
RUN R -q -e "options(repos=c(CRAN='https://cloud.r-project.org')); remotes::install_deps(dependencies=TRUE)"